### ISSUE TITLE
consider migrating recent jazz digital collections into IJC

### ISSUE THREAD

**Issue by evanwill** [uidaholib/ijc-collection-template#3]
- [x] [Ella Fitzgerald](https://www.lib.uidaho.edu/digital/ella-fitzgerald/)
- [x] [Doc Cheatham](https://www.lib.uidaho.edu/digital/cheatham/)
- [x] [Blindfold Tests](https://www.lib.uidaho.edu/digital/blindfold/)
- [x] [Lionel Hampton Jazz Festival Collection](https://www.lib.uidaho.edu/digital/jazzfest/)

Add these collections to the ijc- template and list on IJC home. Don't move from current location on server. Pay attention to `url` value in config.

**Comment by kxuidaho** [comment]
Is this another collection? [Lionel Hampton Jazz Festival Collection](https://www.lib.uidaho.edu/digital/jazzfest/)

**Comment by evanwill** [comment]
yeah, that too!
